directchat/account/urls.py
from django.urls import path, include
from account import views

app_name = 'account'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

directchat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    media_urls = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += media_urls

directchat/core/urls.py
from django.urls import path
from core import views

app_name = 'core'
urlpatterns = [
    path('', views.ChatView.as_view(), name="chat")
]

directchat/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from common.models import BaseModel
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

User = get_user_model()

class Room(BaseModel):
    
    members = models.ManyToManyField(
        to=User, 
        related_name='rooms',
        through='RoomUser',
        verbose_name='members',     
    )
    
    class Meta:
        db_table = 'Room'
        verbose_name = _('room')
        verbose_name_plural = _('rooms')
               
        
class RoomUser(BaseModel):
    
    room = models.ForeignKey(
        to='Room', 
        on_delete=models.CASCADE,
        related_name='room_user_set',      
        verbose_name='room'
    )
    user = models.ForeignKey(
        to=User, 
        on_delete=models.CASCADE,
        related_name='room_user_set',      
        verbose_name='user'
    )
    last_read = models.DateTimeField(
        default=timezone.now,
        verbose_name='last message read time'
    )
      
    class Meta:
        db_table = 'RoomUser'
        verbose_name = _('room_user')
        verbose_name_plural = _('room_user')
        unique_together = ('room', 'user')
        index_together = ('room', 'user')
           
    
class Message(BaseModel):
    author = models.ForeignKey(
        to=User, on_delete=models.CASCADE,
        related_name='messages', verbose_name='author'
    )
    room = models.ForeignKey(
        to='Room', on_delete=models.CASCADE,
        related_name='messages', verbose_name='room'
    )
    text = models.CharField(max_length=1000)
    
    class Meta:
        db_table = 'Message'
        verbose_name = _('message')
        verbose_name_plural = _('messages')

directchat/core/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.urls import reverse


class ChatView(View):
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(
                reverse("account:login") + "?redirect_url=core:chat"
            )
        return super().dispatch(request, *args, **kwargs)

    
    def get(self, request, *args, **kwargs):
        return render(request, 'core/chat.html')

directchat/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<hmtl>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Direct Chat Mini Project</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="{% static 'core/css/chat.css' %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    </head>

    <body>
        <!--###-->
        <div class="edit-profile-div">
            <a href="{% url 'account:profile' %}" target="_blank">Edit Profile</a>&nbsp
            <a href="{% url 'account:logout' %}">logout</a>
        </div>
        <!--###-->
        <div id="container">
			{% block aside %}{% endblock aside %}
            {% block main %}{% endblock main %}

		</div>
		{% block scripts %}{% endblock scripts%}
    </body>

</hmtl>

directchat/core/templates/core/chat.html
{% extends 'core/base.html' %}
{% load static %}

{% block aside%}
<aside>
    <div id="current-user-data"></div><hr>
    <span id="search-username-guide">Enter username to start conversation</span>
    <header>
        <input type="text" placeholder="username" id='search-username' onkeydown="searchUsernameKeydownHandler(event)">
    </header>
    <hr>

    <ul id="contacts"></ul>

</aside>
{% endblock aside %}


{% block main %}
<main>

	<header id="main-header"></header>

	<ul id="chat" onScroll="chatULScrollHandler(event)"></ul>  <!-- The id should not be changed -->

	<footer id='main-footer'></footer>

 </main>
{% endblock main %}


{% block scripts %}
<script async defer src="{% static 'core/js/chat.js' %}"></script>
{% endblock scripts %}